### ISSUE TITLE
Add I-TASSER models

### ISSUE THREAD

**Issue by jchodera** [MolSSI/covid#72]
It would be great to add the I-TASSER models for various viral targets:
https://zhanglab.ccmb.med.umich.edu/COVID-19/

The beautiful image on the top of the page might be useful as well---perhaps we could get permission to use it and have it link to the appropriate proteins?
![image](https://user-images.githubusercontent.com/3656088/79798677-2b739f80-830e-11ea-8492-56e777834036.png)

**Comment by Lnaden** [comment]
I've reached out to the Zhang lab asking about their data and possible reuse of their image.

**Comment by zhanglabs** [comment]
We are trying to add our data by
https://github.com/MolSSI/covid/pull/92
but it was not yet approved due to lack of some SARS-CoV-2 proteins at
https://github.com/MolSSI/covid/tree/master/data/proteins
This is being addressed by our first two commits.
If possible, you can start with accepting our first two commits.

Yang Zhang lab webmaster

**Comment by sjayellis** [comment]
I have added the missing proteins to the validator in #92. This should allow it to pass validation.

**Comment by sjayellis** [comment]
Closing as the models have been added and merged in #92.
