### ISSUE TITLE
Add Swissmodel SARS-CoV-2 models

### ISSUE THREAD

**Issue by jchodera** [MolSSI/covid#73]
The Swissmodel SARS-CoV-2 models may be useful to link:
https://swissmodel.expasy.org/repository/species/2697049

We could link both "all" models (which are useful to browse) as well as specific high-value models for specific targets.

**Comment by gtauriello** [comment]
Hello there. I was pointed to this page by a colleague and I was just about to see how to add our SWISS-MODEL models when I saw this issue. We like the site you have here and are happy to be linked there. So I am happy to help if I can.

Your proposal to add the site directly sounds reasonable and for interesting proteins one can also link directly to the relevant part of that page. I wouldn't link to specific models since the main strength of our page is that we keep it up-to-date every week with the latest PDB release (e.g. we updated it today). As a drawback of that, any direct link to a model will likely not be valid anymore the next week.

Here are direct links to proteins where we have high quality models:
- [nsp7 / nsp8 hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp7-nsp8) -> yml-naming: NSP7 + NSP8
- [nsp7 / nsp8 / Pol hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp7-nsp8-pol) -> yml-naming: NSP7 + NSP8 + RdRP
- [nsp10 / nsp14 hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp10-nsp14) -> yml-naming: NSP10 + NSP14
- [nsp10 / nsp16 hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp10-nsp16) -> yml-naming: NSP10 + NSP16
- [Spike glycoprotein / ACE2_HUMAN hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#P0DTC2-Q9BYF1) -> yml-naming: spike + ACE2
- [Papain-like proteinase (PL-PRO)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp3) -> yml-naming: PLpro
- [Non-structural protein 4 (nsp4)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp4) -> yml-naming: NSP4
- [3C-like proteinase (3CL-PRO)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-3cl) -> yml-naming: 3CLpro
- [Non-structural protein 7 (nsp7)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp7) -> yml-naming: NSP7
- [Non-structural protein 9 (nsp9)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp9) -> yml-naming: NSP9
- [Helicase (Hel)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-helicase) -> yml-naming: NSP13
- [Uridylate-specific endoribonuclease (NendoU/nsp15)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp15) -> yml-naming: NSP15
- [Spike glycoprotein (S glycoprotein)](https://swissmodel.expasy.org/repository/species/2697049#SPIKE_SARS2) -> yml-naming: spike
- [Protein 7a](https://swissmodel.expasy.org/repository/species/2697049#NS7A_SARS2) -> missing yml?
- [Nucleoprotein (NC)](https://swissmodel.expasy.org/repository/species/2697049#NCAP_SARS2) -> missing yml?

All our models come with per-residue model quality estimates to give some confidence on whether or not a region can be trusted. Some of the proteins listed above also have known PDB structures but the models can still be useful to fill gaps in the PDB structures, to cover different parts of the protein or to be in complex with a different ligand.

Additionally to the links, one can also use our SWISS-MODEL Repository to see PDB structures and homology models mapped to a UniProt-sequence in a single view. You can find [a list of all entries here](https://swissmodel.expasy.org/repository/species/2697049/list). It's also possible to link directly to mature proteins cut from the polyprotein ([P0DTD1](https://swissmodel.expasy.org/repository/uniprot/P0DTD1)) and I can tell you more about it if you are interested.

Also if you need any help in keeping the list of PDBs up to date, let me know. We have some experience with how to parse PDB-data and SIFTS-mappings...

**Comment by Lnaden** [comment]
Excellent news! 

For the missing YAML proteins, those can just be added like any structure. They auto populate to the site like most everything else.

The model's being invalid is an interesting issue. Since our site is statically generated, we can't keep the links live in real time, but we can schedule simple cron jobs to rebuild it nightly or something. As for getting the most recent data, is there some regular file(s) which your site pulls its data from to populate (e.g. JSON or other REST-API-like data)? If so, we can possibly just pull in data from there.

What happens to the old links of models which expire from week to week? Are the old links just replaced with new ones for more up to date models? If so, would it be possible to have a symlink-like url which just points to "latest," or does that not work well here?

We are very excited to have these models and structures in the Hub and are happy to take any suggestions you might have about improvements we can make. We're also happy to help get the data in as well, just let us know what you need.

**Comment by gtauriello** [comment]
The links I provided above are stable. We update the text and models weekly but the links are stable. So that should work. They don't go straight to pdb files though and that's on purpose.

I would prefer if on this page, we don't link directly to pdb files for our models. While we do have some API-functionalities to fetch pdb files directly from our repository which we could use for this purpose, I simply would advice against it. We believe that models (independently from the provider) always need to be used with care and so users should be able to check the model quality estimates and then fetch and use the coordinates. This works best if they look at the models on our page directly...

**Comment by Lnaden** [comment]
Thanks for the info, and I very much understand that sentiment. Is it my understanding then you would prefer the base structures (in the links you provided above) be linked to, and then for the "models" page on our side, we can simply re-use the links and annotate that these are constantly updating?

**Comment by gtauriello** [comment]
Yes exactly.

**Comment by jchodera** [comment]
> We believe that models (independently from the provider) always need to be used with care and so users should be able to check the model quality estimates and then fetch and use the coordinates. This works best if they look at the models on our page directly...

@gtauriello : The main purpose of the MolSSI repo is to provide some curation to direct users quickly to the best models for particular targeting opportunities (e.g. identifying compounds against the Mpro dimer interface, or ATP-competitive inhibitors for the ATP-bound form of nsp13). What would you think of (1) identifying a few key models that you believe are "highly useful" for specific targeting purposes and promoting those in particular for particular targets, and (2) potentially considering joining our model curation team!

**Comment by gtauriello** [comment]
Ok. Here a shortened version of the list above with notes on how the models were useful:
- [Helicase (Hel)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-helicase) -> yml-naming: NSP13
(no PDB structures available yet)
- [nsp10 / nsp14 hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp10-nsp14) -> yml-naming: NSP10 + NSP14
(no PDB structures available yet)
- [Non-structural protein 4 (nsp4)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp4) -> yml-naming: NSP4
(no PDB structures available yet)
- [Protein 7a](https://swissmodel.expasy.org/repository/species/2697049#NS7A_SARS2) -> missing yml?
(no PDB structures available yet)
- [Papain-like proteinase (PL-PRO)](https://swissmodel.expasy.org/repository/species/2697049#R1AB_SARS2-nsp3) -> yml-naming: PLpro
(we cover some domains not covered by PDB structures so far)
- [Spike glycoprotein / ACE2_HUMAN hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#P0DTC2-Q9BYF1) -> yml-naming: spike + ACE2
(hetero-model of full length prefusion state as opposed to only receptor binding domain in PDB structures so far)
- [Spike glycoprotein (S glycoprotein)](https://swissmodel.expasy.org/repository/species/2697049#SPIKE_SARS2) -> yml-naming: spike
(collaborators have used our models (e.g. based on PDB structure 6vsb) to fill gaps)
- [nsp7 / nsp8 / Pol hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp7-nsp8-pol) -> yml-naming: NSP7 + NSP8 + RdRP
(collaborators have used our models (e.g. based on PDB structure 7btf) to fill gaps)
- [nsp7 / nsp8 hetero-oligomeric complex](https://swissmodel.expasy.org/repository/species/2697049#nsp7-nsp8) -> yml-naming: NSP7 + NSP8
(full length nsp8 has different stoichiometry than shortened version in available PDB structure 6wiq)

**Comment by gtauriello** [comment]
In terms of joining the model curation team, my feeling is that it's good if this data collection effort stays independent and so it's better not to add modellers in the mix which could introduce biases... ;-)

**Comment by gtauriello** [comment]
btw: I did some edits on the lists above given the last update we did with yesterday's PDB release...

**Comment by sjayellis** [comment]
@gtauriello 
We have opened a PR with a first pass at adding the models you have listed. #123 
We have currently left the model descriptions fairly generic, since the models may be updated and/or changed as time goes on.

If you would like to review them and either make changes to the yaml files added in the PR or suggest changes here I would be happy to make updates.

**Comment by gtauriello** [comment]
@sjayellis That's great. Thank you. I think it's good to keep the description vague. I would propose the following changes to the texts which can be applied to each yaml file:
```
description: Full SARS-CoV-2 proteome modeled. Follow the Model link for weekly updated models and PDB structures. All models include global and per-residue quality estimates.
creator: SWISS-MODEL team
institution: Swiss Institute of Bioinformatics, Biozentrum, University of Basel
```
Would that work?

I also checked the models again with yesterday's PDB update and the 9 entries that you added are still good.

**Comment by gtauriello** [comment]
Also if you want something to the contributors list, I would propose a single entry for "Schwede Group" with a link to http://schwedelab.org

Actually above we could put "SWISS-MODEL team, Schwede Group" as "creator" for the models to be consistent. Either way is ok...

**Comment by sjayellis** [comment]
I have added a contributor entry and updated the creator tag for each of the files. I have also added the rest of the models you first mentioned that have associated proteins. If you think these look good I will go ahead and get them merged onto the live site.

**Comment by gtauriello** [comment]
Yes this looks good to me. Thanks.

**Comment by sjayellis** [comment]
After looking into it a bit more we do have the two proteins listed as missing. Protein 7a is under ORF7a and Nucleoprotein is listed as N protein. I have added the last two models to the PR and we will get those merged in.

I will close this issue as we now have all the models added.
